// <auto-generated />
namespace MyWorkshop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class just_trying_everything_to_fix_this_sh_t : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(just_trying_everything_to_fix_this_sh_t));
        
        string IMigrationMetadata.Id
        {
            get { return "201705081142501_just_trying_everything_to_fix_this_sh_t"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
