// <auto-generated />
namespace MyWorkshop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class models_global_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(models_global_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201705060812340_models_global_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
