// <auto-generated />
namespace MyWorkshop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Image_Album_Fields_Renamed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Image_Album_Fields_Renamed));
        
        string IMigrationMetadata.Id
        {
            get { return "201704291703170_Image_Album_Fields_Renamed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
