// <auto-generated />
namespace MyWorkshop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class another_bug_with_EF_migrations_trying_to_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(another_bug_with_EF_migrations_trying_to_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201705091347088_another_bug_with_EF_migrations_trying_to_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
