// <auto-generated />
namespace MyWorkshop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class second_try_to_implement_fluen_api : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(second_try_to_implement_fluen_api));
        
        string IMigrationMetadata.Id
        {
            get { return "201705151639395_second_try_to_implement_fluen_api"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
